movierating/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.detail, name="details"),
    path('addmovies/', views.add_movie, name="add_movie"),
    path('addreview/<int:id>/', views.addReview, name="add_review"),
    path('addreleasedate/<int:id>/', views.add_release_date, name="add_release_date"),
    path('addsoundtrack/<int:id>/', views.add_soundtrack, name="add_soundtrack"),
    path('addproduction/<int:id>/', views.add_production, name="add_production"),
    path('addawardandcategory/<int:id>/', views.add_award_and_category, name="add_award_and_category"),
    path('addmoviecast/<int:id>/', views.add_movie_cast, name="add_movie_cast"),
    path('addmoviecrew/<int:id>/', views.add_movie_crew, name="add_movie_crew"),
    path('addgenre/<int:id>/', views.add_genre, name="add_genre"),
    path('editmovie/<int:id>/', views.edit_movie, name="edit_movie"),
    path('deletemovie/<int:id>/', views.delete_movie, name="delete_movie"),
    path('editreleasedate/<int:id>/', views.edit_release_date, name="edit_release_date"),
    path('editsoundtrack/<int:movie_id>/<int:key_id>/', views.edit_soundtrack, name="edit_soundtrack"),
    path('addsoundtrack/<int:id>/', views.add_soundtrack, name="add_soundtrack"),
    path('addkeywords/<int:id>/', views.add_keywords, name="add_keywords"),
    path('addcountry/<int:id>/', views.add_country, name="add_country"),
    path('addrating/<int:id>/', views.addRating, name="add_rating"),
    path('editmovie/<int:id>/', views.edit_movie, name="edit_movie"),
    path('editreleasedate/<int:id>/', views.edit_release_date, name="edit_release_date"),
    path('editsoundtrack/<int:id>/', views.edit_soundtrack, name="edit_soundtrack"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('editkeywords/<int:movie_id>/<int:key_id>/', views.edit_keywords, name="edit_keywords"),
    path('editcountry/<int:movie_id>/<int:key_id>/', views.edit_country, name="edit_country"),
    path('editcountry/<int:id>/', views.edit_country, name="edit_country"),
    path('editgenre/<int:movie_id>/<int:key_id>/', views.edit_genre, name="edit_genre"),
    path('editawardandcategory/<int:movie_id>/<int:award_id>/<int:category_id>/', views.edit_award_and_category, name="edit_award_and_category"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review"),
    path('deletemovie/<int:id>/', views.delete_movie, name="delete_movie"),
    path('deletekeywords/<int:id>/<int:key_id>/', views.delete_keywords, name="delete_keywords"),
    path('deleteawardandcategory/<int:movie_id>/<int:award_id>/<int:category_id>/', views.delete_award_and_category, name="delete_award_and_category"),
    path('deletegenre/<int:movie_id>/<int:key_id>/', views.delete_genre, name="delete_genre"),
    path('deletecountry/<int:movie_id>/<int:key_id>/', views.delete_country, name="delete_country"),
    path('deleteproduction/<int:movie_id>/<int:key_id>/', views.delete_production, name="delete_production"),
    path('deletereleasedates/<int:movie_id>/', views.delete_release_date, name="delete_release_date"),
    path('deletesoundtrack/<int:movie_id>/<int:soundtrack_id>/', views.delete_soundtrack, name="delete_soundtrack"),
    path('deletemoviecast/<int:movie_id>/<int:character_id>/<int:person_id>/<int:gender_id>/', views.delete_movie_cast, name="delete_movie_cast"),
    path('deletemoviecrew/<int:movie_id>/<int:person_id>/<int:department_id>/', views.delete_movie_crew, name="delete_movie_crew")
    # path('add_info/<int:id>/', views.addInfo, name="add_info")
]

movierating/movierating/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('main.urls'))
]

movierating/main/forms.py
from django import forms
from .models import *


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'budget', 'runtime', 'avg_rank', 'summary', 'revenue', 'language', 'image')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = review
        fields = ('review',)


class ReleaseDateForm(forms.ModelForm):
    class Meta:
        model = release_dates
        fields = ('country', 'release_date')


class SoundtrackForm(forms.ModelForm):
    class Meta:
        model = soundtrack
        fields = ('soundtrack_name', 'writer_name', 'singer')


class KeywordsForm(forms.ModelForm):
    class Meta:
        model = keywords
        fields = ('keyword_name',)


class CountryNameForm(forms.ModelForm):
    class Meta:
        model = country_name
        fields = ('country_name',)


class RatingForm(forms.ModelForm):
    class Meta:
        model = ratings
        fields = ('rating',)

class ProductionForm(forms.ModelForm):
    class Meta:
        model = production
        fields = ('production_name',)


class AwardForm(forms.ModelForm):
    class Meta:
        model = award_name
        fields = ('award_name', 'year')


class AwardCategoryForm(forms.ModelForm):
    class Meta:
        model = category_name
        fields = ('category_name',)


class PersonForm(forms.ModelForm):
    class Meta:
        model = person
        fields = ('person_name', 'person_lastname', 'person_birthdate', 'person_deathdate')


class RoleForm(forms.ModelForm):
    class Meta:
        model = character_role
        fields = ('role', 'character_name', 'character_order')


class GenderForm(forms.ModelForm):
    class Meta:
        model = gender
        fields = ('gender',)


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = departments
        fields = ('department_name', 'job')


class KeywordsForm(forms.ModelForm):
    class Meta:
        model = keywords
        fields = ('keyword_name',)


class CountryNameForm(forms.ModelForm):
    class Meta:
        model = country_name
        fields = ('country_name',)


class RatingForm(forms.ModelForm):
    class Meta:
        model = ratings
        fields = ('rating',)


class GenreForm(forms.ModelForm):
    class Meta:
        model = genres
        fields = ('genre',)

movierating/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.

def home(request):
    allMovies = Movie.objects.all()
 
    context = {
        "movies": allMovies,
    }

    return render(request, 'main/index.html', context)

# detail page

def detail(request, id):
    movie = Movie.objects.get(movie_id=id)
    reviews = review.objects.filter(movie_id=id)
    rds = release_dates.objects.filter(movie_id=id)

    # country section
    ct = countries.objects.filter(movie_id=movie)
    ct_list = []
    for j in ct:
        ctx = j.country_id
        ct_list.append(ctx)
    
    # production section
    pd = production_company.objects.filter(movie_id=movie)
    pd_list = []
    for l in pd:
        pdx = l.production_id
        pd_list.append(pdx)
    
    # key words section
    kw = movie_keywords.objects.filter(movie_id=movie)
    kw_list = []
    for i in kw:
        kwx = i.keyword_id
        kw_list.append(kwx)

    #soundtrack section
    soundtrack2 = movie_soundtrack.objects.filter(movie_id=movie)
    soundtracks = []
    for i in soundtrack2:
        soundtrack_name=i.soundtrack_id
        soundtracks.append(soundtrack_name)

    # genre section
    genre = movie_genre.objects.filter(movie_id=movie)
    genre_list = []
    for i in genre:
        kwx = i.genre_id
        genre_list.append(kwx)


    # award section
    award = awards.objects.filter(movie_id=movie)
    award_dict = {}
    count = 0
    for i in award:
        award_dict[award[count].award_id] = award[count].category_id
        count = count +1

    # cast section
    cast = movie_cast.objects.filter(movie_id=movie)
    cast_list = []
    for j in cast:
        cast_list.append(j)

    # crew section
    crew = movie_crew.objects.filter(movie_id=movie)
    crew_list = []
    for j in crew:
        crew_list.append(j)

    context = {
        "movie": movie,
        "reviews": reviews,
        "keywords": kw_list,
        "soundtrack": soundtracks,
        "country": ct_list,
        "release_dates": rds,
        "genres": genre_list,
        "productions": pd_list,
        "awards": award_dict,
        "cast": cast_list,
        "crew": crew_list
    }
    return render(request, 'main/details.html', context)


def add_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = MovieForm()
    return render(request, 'main/addmovies.html', {"form": form})


def addInfo(request, id):
    movie = Movie.objects.get(id=id)

    context = {
        "movie": movie
    }
    return render(request, 'main/add_info.html', context)


def addReview(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(movie_id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.review = request.POST["review"]
                data.user_id = request.user
                data.movie_id = movie
                data.save()
                return redirect("main:home")
        else:
            form = ReviewForm()
        return render(request, 'main/index.html', {"form": form})
    else:
        return redirect("main:home")


def addRating(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(movie_id=id)
        if request.method == "POST":
            form = RatingForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.user_id = request.user
                if ratings.objects.filter(user_id=request.user, movie_id=movie).exists() is False:
                    if (data.rating <= 10) or (data.rating > 0):
                        data.save()
                        data.movie_id.add(movie)
                        x = ratings.objects.filter(movie_id=movie).all()
                        y = 0
                        count = 0
                        for i in x:
                            y = y + i.rating
                            count = count+1
                        avgR = y/count
                        Movie.objects.filter(movie_id=id).update(avg_rank=avgR)
                        return redirect("main:home")
                    else:
                        error = "Out of range. Select a rating between 0 and 10."
                        return render(request, 'main/add_rating.html', {"error": error, "form": form})
                else:
                    error = "You can't rate the same movie more than once."
                    return render(request, 'main/add_rating.html', {"error": error, "form": form})
        else:
            form = RatingForm()
        return render(request, 'main/add_rating.html', {"form": form})
    else:
        return redirect("main:home")


def add_release_date(request, id):
    movie = Movie.objects.get(movie_id=id)
    if request.method == "POST":
        form = ReleaseDateForm(request.POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            if release_dates.objects.filter(movie_id=movie, country=data.country, release_date=data.release_date).exists() is True:
                error = "This entry already exists! Try again with a new one."
                return render(request, 'main/add_release_date.html', {"error": error, "form": form})
            data.save()
            data.movie_id.add(movie)
            return redirect("main:details", id)
    else:
        form = ReleaseDateForm()
    return render(request, 'main/add_release_date.html', {"form": form})


def add_soundtrack(request, id):
    movie = Movie.objects.get(movie_id=id)
    if request.method == "POST":
        form = SoundtrackForm(request.POST or None)

        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            st = soundtrack.objects.latest('soundtrack_id')
            ms = movie_soundtrack(soundtrack_id=st)
            ms.save()
            ms.movie_id.add(movie)
            return redirect("main:details", id)
    else:
        form = SoundtrackForm()
    return render(request, 'main/add_soundtrack.html', {"form": form})


def add_keywords(request, id):
    movie = Movie.objects.get(movie_id=id)
    if request.method == "POST":
        form = KeywordsForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            y = movie_keywords.objects.filter(movie_id=movie)
            y_value = False
            for j in y:
                yx = j.keyword_id
                if (yx.keyword_name == data.keyword_name):
                    error = "This entry already exists! Try again with a new one."
                    return render(request, 'main/add_keywords.html', {"error": error, "form": form})
            data.save()
            kw = keywords.objects.latest('keyword_id')
            mk = movie_keywords(keyword_id=kw)
            mk.save()
            mk.movie_id.add(movie)
            return redirect("main:details", id)
    else:
        form = KeywordsForm()
    return render(request, 'main/add_keywords.html', {"form": form})


def add_country(request, id):
    movie = Movie.objects.get(movie_id=id)
    if request.method == "POST":
        form = CountryNameForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            y = countries.objects.filter(movie_id=movie)
            y_value = False
            for j in y:
                yx = j.country_id
                if (yx.country_name == data.country_name):
                    error = "This entry already exists! Try again with a new one."
                    return render(request, 'main/add_country.html', {"error": error, "form": form})
            data.save()
            ct = country_name.objects.latest('country_id')
            cts = countries(country_id=ct)
            cts.save()
            cts.movie_id.add(movie)
            return redirect("main:details", id)
    else:
        form = CountryNameForm()
    return render(request, 'main/add_country.html', {"form": form})


def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(movie_id=movie_id)
        Review = review.objects.get(movie_id=movie, id=review_id)

        if request.user == Review.user_id:
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=Review)
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:details", movie_id)
            else:
                form = ReviewForm(instance=Review)
            return render(request, 'main/edit_review.html', {"form": form})
        else:
            return redirect("main:details", movie_id)
    else:
        return redirect("main:home")


def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(movie_id=movie_id)
        Review = review.objects.get(movie_id=movie, id=review_id)

        if request.user == Review.user_id:
            Review.delete()
        
        return redirect("main:details", movie_id)
    else:
        return redirect("main:home")


def edit_keywords(request, movie_id, key_id):
    movie = Movie.objects.get(movie_id=movie_id)
    # kid = movie_keywords.objects.get(movie_id=movie)
    kinfo = keywords.objects.get(keyword_id=key_id)
    if request.method == "POST":
        form = KeywordsForm(request.POST or None, instance=kinfo)

        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:details", movie_id)
    else:

movierating/main/templates/main/add_info.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <h1 class="text-center">Add More Info</h1>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/add_keywords.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Keywords</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Add Keywords">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/add_production.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-content">
                <h3 class="text-center">Add Production</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {% if error %}
                        <strong style="color: red;">{{ error }}</strong>
                    {% endif %}
                    <input type="submit" value="Add Production">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

movierating/main/templates/main/add_release_date.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Release Date</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Add Release Date">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/add_soundtrack.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Soundtrack</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Add Soundtrack">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/addmovies.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Movie</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Add Movie">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/details.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ movie.image }}" alt="{{ movie.title }}" class="img-fluid">
                </div>
                <div class="col-md-8">
                    <h3 class="text-center">
                        {{ movie.title }}
                    </h3>
                    <br>
                    {% if user.is_superuser %}
                    <a href="{% url 'main:edit_movie' movie.movie_id %}" class="btn btn-warning">Edit Movie</a>
                    <a href="{% url 'main:delete_movie' movie.movie_id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this entry?');">Delete Movie</a>
                    <br>
                    <br>
                    <a href="{% url 'main:add_release_date' movie.movie_id %}" class="btn btn-warning">Add Release Date</a>
                    <a href="{% url 'main:add_keywords' movie.movie_id %}" class="btn btn-warning">Add Keywords</a>
                    <a href="{% url 'main:add_genre' movie.movie_id %}" class="btn btn-warning">Add Genre</a>
                    <a href="{% url 'main:add_award_and_category' movie.movie_id %}" class="btn btn-warning">Add Awards</a>
                    <a href="{% url 'main:add_country' movie.movie_id %}" class="btn btn-warning">Add Country</a>
                    <br>
                    <br>
                    <a href="{% url 'main:add_soundtrack' movie.movie_id %}" class="btn btn-warning">Add Soundtrack</a>
                    <a href="{% url 'main:add_production' movie.movie_id %}" class="btn btn-warning">Add Production</a>
                    <a href="{% url 'main:add_movie_cast' movie.movie_id %}" class="btn btn-warning">Add Movie Cast</a>
                    <a href="{% url 'main:add_movie_crew' movie.movie_id %}" class="btn btn-warning">Add Movie Crew</a>
                    {% endif %}
                    <br>
                    <br>
                    <h5>Summary</h5>
                    <p>{{ movie.summary }}</p>
                    <h5>Budget: {{ movie.budget }}$</h5>
                    <h5>Revenue: {{ movie.revenue }}$</h5>
                    <h5>Runtime: {{ movie.runtime }} hrs</h5>
                    <h5>Language: {{ movie.language }}</h5>
                    <h5>Rating: {{ movie.avg_rank }}</h5>
                    <br>
                    <h6>Release Dates: </h6>
                    {% for rd in release_dates %}
                    <li>{{ rd.release_date }} <i>--{{ rd.country }}</i></li>
                    {% if user.is_superuser %}
                        <a href="{% url 'main:edit_release_date' movie.movie_id %}">Edit</a>
                        <a href="{% url 'main:delete_release_date' movie.movie_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Keywords: </h6>
                    {% for keyword in keywords %}
                    <li>{{ keyword.keyword_name }}</li>
                    {% if user.is_superuser %}
                    <a href="{% url 'main:edit_keywords' movie.movie_id keyword.keyword_id %}">Edit</a>
                    <a href="{% url 'main:delete_keywords' movie.movie_id keyword.keyword_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Genres: </h6>
                    {% for genre in genres %}
                    <li>{{ genre.genre }}</li>
                    {% if user.is_superuser %}
                    <a href="{% url 'main:edit_genre' movie.movie_id genre.genre_id %}">Edit</a>
                    <a href="{% url 'main:delete_genre' movie.movie_id genre.genre_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Awards: </h6>
                    {% for k, v in awards.items %}
                    <li>{{ k.award_name }}: {{ v.category_name }}</li>
                    {% if user.is_superuser %}
                    <a href="{% url 'main:edit_award_and_category' movie.movie_id k.award_id v.category_id %}">Edit</a>
                    <a href="{% url 'main:delete_award_and_category' movie.movie_id k.award_id v.category_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Soundtracks: </h6>
                    {% for st in soundtrack %}
                    <li>{{ st.soundtrack_name }}- Written by: {{ st.writer_name }}, Performed by: {{ st.singer }}</li>
                    {% if user.is_superuser %}
                    <a href="{% url 'main:edit_soundtrack' movie.movie_id st.soundtrack_id %}">Edit</a>
                    <a href="{% url 'main:delete_soundtrack' movie.movie_id st.soundtrack_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Country: </h6>
                    {% for c in country %}
                    <li>{{ c.country_name }}</li>
                    {% if user.is_superuser %}
                        <a href="{% url 'main:edit_country' movie.movie_id c.country_id %}">Edit</a>
                        <a href="{% url 'main:delete_country' movie.movie_id c.country_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Production: </h6>
                    {% for pr in productions %}
                    <li>{{ pr.production_name }}</li>
                    {% if user.is_superuser %}
                        <a href="{% url 'main:delete_production' movie.movie_id pr.production_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Movie Cast: </h6>
                    {% for c in cast %}
                    <p>--{{ c.person_id.person_name }} {{c.person_id.person_lastname}},
                        Character name: {{ c.character_id.character_name }}, 
                        Character Role: {{ c.character_id.character_role }}, 
                        Character order:  {{ c.character_id.character_order }}, 
                        Birthdate: {{ c.person_id.person_birthdate }}, 
                        Gender: {{ c.gender_id.gender }} 
                    </p>
                    {% if user.is_superuser %}
                        <a href="{% url 'main:delete_movie_cast' movie.movie_id c.character_id.character_id c.person_id.person_id c.gender_id.gender_id  %}"onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                    <br>
                    <h6>Movie Crew: </h6>
                    {% for c in crew %}
                    <p>--{{ c.person_id.person_name }} {{c.person_id.person_lastname}}, 
                        Birthdate: {{ c.person_id.person_birthdate }}, 
                        Department: {{ c.department_id.department_name }}, 
                        Job: {{ c.department_id.job }} 
                    </p>
                    {% if user.is_superuser %}
                        <a href="{% url 'main:delete_movie_crew' movie.movie_id c.person_id.person_id c.department_id.department_id %}" onclick="return confirm('Are you sure you want to delete this entry?');">Delete</a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            <ul>
                {% for review in reviews %}
                <li>{{ review.review }} <i>--{{ review.user_id}}</i></li>
                {% if request.user == review.user_id %}
                <a href="{% url 'main:edit_review' movie.movie_id review.id %}">Edit</a>
                <a href="{% url 'main:delete_review' movie.movie_id review.id %}" onclick="return confirm('Are you sure you want to delete this review?');">Delete</a>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'main:add_review' movie.movie_id %}" method="POST">
                {% csrf_token %}
                <label for="review">Review</label>
                <textarea name="review" id="review" cols="30" rows="10" class="form-control"></textarea>
                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    {% endif%}


</div>

{% endblock %}

movierating/main/templates/main/edit_award_and_category.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-content">
                <h3 class="text-center">Edit Awards</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ form2|crispy }}
                    <input type="submit" value="Edit Awards">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

movierating/main/templates/main/edit_keywords.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Edit Keywords</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Save Changes">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movierating/main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <h3 class="text center">{{ movie.title }}</h3>
                            </div>
                            <br>
                            <div class="text-center">
                                <img src="{{ movie.image }}" alt="" class="img-fluid" style="max-width:100%; max-height: 400px;">
                            </div>
                            <a href="{% url 'main:add_rating' movie.movie_id %}" class="btn btn-warning">Rate</a>
                            <a href="{% url 'main:details' movie.movie_id %}" class="btn btn-warning">Details</a>
                        </div>
                    </div>
                </div>
                {% endfor%}
            </div>
        </div>
    </div>
</div>

{% endblock %}